networks:
  telegram-bot-app:
    driver: bridge
services:
  pgsql:
    container_name: pgsql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    networks:
      - telegram-bot-app
    volumes:
      - pgsql-data:/var/lib/postgresql/data
volumes:
  pgsql-data: